export const initialState={
    "drinks": [ 
        // {
//   idDrink: "",
//   strDrink: "",
//   strDrinkAlternate: null,
//   strTags: null,
//   strVideo: null,
//   strCategory: "",
//   strIBA: null,
//   strAlcoholic: "",
//   strGlass: "",
//   strInstructions: "",
//   strInstructionsES: "",
//   strInstructionsDE: "",
//   strInstructionsFR: "",
//   strInstructionsIT: "",
//   "strInstructionsZH-HANS": null,
//   "strInstructionsZH-HANT": null,
//   strDrinkThumb: "",
//   strIngredient1: null,
//   strIngredient2: null,
//   strIngredient3: null,
//   strIngredient4: null,
//   strIngredient5: null,
//   strIngredient6: null,
//   strIngredient7: null,
//   strIngredient8: null,
//   strIngredient9: null,
//   strIngredient10: null,
//   strIngredient11: null,
//   strIngredient12: null,
//   strIngredient13: null,
//   strIngredient14: null,
//   strIngredient15: null,
//   strMeasure1: null,
//   strMeasure2: null,
//   strMeasure3: null,
//   strMeasure4: null,
//   strMeasure5: null,
//   strMeasure6: null,
//   strMeasure7: null,
//   strMeasure8: null,
//   strMeasure9: null,
//   strMeasure10: null,
//   strMeasure11: null,
//   strMeasure12: null,
//   strMeasure13: null,
//   strMeasure14: null,
//   strMeasure15: null,
//   strImageSource: null,
//   strImageAttribution: null,
//   strCreativeCommonsConfirmed: "",
//   dateModified: "",
// }
]
}

